#!/usr/bin/env bash
# Displays the information about subdomains

get_dns_info() {
    local domain=$1
    local subdomain=$2
    local full_domain=$subdomain.$domain

    # Fetch A record
    local a_record
    a_record=$(dig +short -t A "$full_domain")

    # Check if the A record exists and output the result
    if [[ -n $a_record ]]; then
        echo "The subdomain $subdomain is a A record and points to $a_record"
    else
        echo "No A record found for $subdomain"
    fi
}

# Main script logic
domain=$1
subdomain=$2

if [[ -n $subdomain ]]; then
    # Fetch information for the specified subdomain
    get_dns_info "$domain" "$subdomain"
else
    # Default subdomains
    for sub in "www" "lb-01" "web-01" "web-02"; do
        get_dns_info "$domain" "$sub"
    done
fi
