#!/usr/bin/env bash
# Installs NGINX on a server and configures a 301 redirect

sudo apt update
sudo apt install -y nginx

# Ensure NGINX is started
sudo service nginx start

# Configure NGINX for custom page and redirect
printf "server {
    listen 80;

    location / {
        return 200 'Hello World!\n';
        add_header Content-Type text/plain;
    }

    location /redirect_me {
        return 301 http://google.com;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Test NGINX configuration
sudo nginx -t

# Restart NGINX without using systemctl
sudo service nginx restart
