#!/usr/bin/env bash
# Installs NGINX on a server, configures a 301 redirect, and sets a custom 404 page

sudo apt update
sudo apt install -y nginx

# Ensure NGINX is started
sudo service nginx start

# Configure NGINX for custom page, redirect, and custom 404 error page
sudo tee /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80;

    # Custom 404 page
    error_page 404 /custom_404;
    
    location = /custom_404 {
        add_header Content-Type text/plain;
        return 404 'Ceci n\'est pas une page\n';
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 http://google.com;
    }

    # Return Hello World for the root URL
    location = / {
        return 200 'Hello World!\n';
        add_header Content-Type text/plain;
    }
}
EOF

# Test NGINX configuration
sudo nginx -t

# Restart NGINX without using systemctl
sudo service nginx restart
