#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

# MySQL credentials
MYSQL_USER="root"
MYSQL_PASS="$1"

# File names
BACKUP_FILE="backup.sql"
DATE=$(date +%d-%m-%Y)
ARCHIVE_FILE="${DATE}.tar.gz"

# Create MySQL dump
mysqldump -u root -p"$1" --all-databases > backup.sql
# Compress the dump file
tar -czf $DATE.tar.gz backup.sql
