#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name, of processes whose name contain the word bash

for pid in /proc/[0-9]*
do
  if [[ -e "$pid/cmdline" ]]
  then
    cmdline=$(< "$pid/cmdline" tr '\0' ' ' | tr -d '\n')
    
    if [[ "$cmdline" == *"bash"* ]]
    then
      echo "$(basename "$pid") bash"
    fi
  fi
done