#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for i in {1..10}
do
        if [ "$i" -eq 9 ]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
        fi
done