#!/usr/bin/env bash
# Bash script that displays the content of the current directory in a list format

ls > list

for i in $(cat list)
do
	echo "$i" | awk -F '-' '{ for (j=2; j<=NF; ++j) printf "%s%s", $j, (j==NF?ORS:OFS) }'
done
